"""add adjectives

Revision ID: 05db262f4283
Revises: 68f32b4c1080
Create Date: 2025-04-09 19:49:38.270280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '05db262f4283'
down_revision: Union[str, None] = '68f32b4c1080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masc_french_singular', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fem_french_singular', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('masc_french_plural', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fem_french_plural', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('english_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adjective')
    # ### end Alembic commands ###
