"""Add English Text to Verb

Revision ID: 68f32b4c1080
Revises: d09e7abcbc92
Create Date: 2025-03-17 12:38:07.118675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '68f32b4c1080'
down_revision: Union[str, None] = 'd09e7abcbc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frenchverb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('english_text', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frenchverb', schema=None) as batch_op:
        batch_op.drop_column('english_text')

    # ### end Alembic commands ###
